config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :funds
  resources :funds do
    get 'searches', on: :collection
  end

  root to: 'visitors#index'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/fund.rb
class Fund < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/funds_controller.rb
class FundsController < InheritedResources::Base

  def searches
  end

  private

    def fund_params
      params.require(:fund).permit(:materia, :ministerio, :servicio_publico, :nombre, :objetivo, :postulacion_quienes, :postulacion_cuando, :postulacion_como, :comunidades_indigenas, :municipalidades, :asociaciones, :personas_naturales, :personas_juridicas_con_fines_de_lucro, :personas_juridicas_sin_fines_de_lucro, :donde_se_postula, :areas_tematicas_de_financiamiento, :monto_minimo, :monto_maximo, :requisitos_para_postular, :contacto, :organizaciones_participantes)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/twitter'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/views/funds/_form.html.haml
= form_for @fund do |f|
  - if @fund.errors.any?
    #error_explanation
      %h2= "#{pluralize(@fund.errors.count, "error")} prohibited this fund from being saved:"
      %ul
        - @fund.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :materia
    = f.text_field :materia
  .field
    = f.label :ministerio
    = f.text_field :ministerio
  .field
    = f.label :servicio_publico
    = f.text_field :servicio_publico
  .field
    = f.label :nombre
    = f.text_field :nombre
  .field
    = f.label :objetivo
    = f.text_field :objetivo
  .field
    = f.label :postulacion_quienes
    = f.text_field :postulacion_quienes
  .field
    = f.label :postulacion_cuando
    = f.text_field :postulacion_cuando
  .field
    = f.label :postulacion_como
    = f.text_field :postulacion_como
  .field
    = f.label :comunidades_indigenas
    = f.check_box :comunidades_indigenas
  .field
    = f.label :municipalidades
    = f.check_box :municipalidades
  .field
    = f.label :asociaciones
    = f.check_box :asociaciones
  .field
    = f.label :personas_naturales
    = f.check_box :personas_naturales
  .field
    = f.label :personas_juridicas_con_fines_de_lucro
    = f.check_box :personas_juridicas_con_fines_de_lucro
  .field
    = f.label :personas_juridicas_sin_fines_de_lucro
    = f.check_box :personas_juridicas_sin_fines_de_lucro
  .field
    = f.label :donde_se_postula
    = f.text_field :donde_se_postula
  .field
    = f.label :areas_tematicas_de_financiamiento
    = f.text_field :areas_tematicas_de_financiamiento
  .field
    = f.label :monto_minimo
    = f.text_field :monto_minimo
  .field
    = f.label :monto_maximo
    = f.text_field :monto_maximo
  .field
    = f.label :requisitos_para_postular
    = f.text_field :requisitos_para_postular
  .field
    = f.label :contacto
    = f.text_field :contacto
  .field
    = f.label :organizaciones_participantes
    = f.check_box :organizaciones_participantes
  .actions
    = f.submit 'Save'

app/views/funds/edit.html.haml
%h1 Editing fund

= render 'form'

= link_to 'Show', @fund
\|
= link_to 'Back', funds_path

app/views/funds/index.html.haml
%div.container
  %div
    %ol.breadcrumb
      %li
        %a{href: '/'}
          portada
      %li
        = link_to 'descúbrete', page_path('discover')
      %li
        = link_to 'existe', page_path('exist')
      %li.active
        funciona

  %h2.page-header Funciona

  %table.table.table-striped#funds
    %thead
      %tr
        %th Materia
        %th Ministerio
        %th Servicio publico
        %th Nombre
        %th Objetivo
        %th Postulacion quienes
        %th Postulacion cuando
        %th Postulacion como
    
    %tbody
      - @funds.each do |fund|
        %tr
          %td= fund.materia
          %td= fund.ministerio
          %td= fund.servicio_publico
          %td= fund.nombre
          %td= fund.objetivo
          %td= fund.postulacion_quienes
          %td= fund.postulacion_cuando
          %td= fund.postulacion_como

:javascript
  $(document).ready(function(){
    $('#funds').DataTable({
      "order": [[ 1, "desc" ]],
      "columnDefs": [
          {
              "targets": [ 4 ],
              "visible": false,
              "searchable": true
          }
      ]
    });
  });

app/views/funds/new.html.haml
%h1 New fund

= render 'form'

= link_to 'Back', funds_path

app/views/funds/show.html.haml
%p#notice= notice

%p
  %b Materia:
  = @fund.materia
%p
  %b Ministerio:
  = @fund.ministerio
%p
  %b Servicio publico:
  = @fund.servicio_publico
%p
  %b Nombre:
  = @fund.nombre
%p
  %b Objetivo:
  = @fund.objetivo
%p
  %b Postulacion quienes:
  = @fund.postulacion_quienes
%p
  %b Postulacion cuando:
  = @fund.postulacion_cuando
%p
  %b Postulacion como:
  = @fund.postulacion_como
%p
  %b Comunidades indigenas:
  = @fund.comunidades_indigenas
%p
  %b Municipalidades:
  = @fund.municipalidades
%p
  %b Asociaciones:
  = @fund.asociaciones
%p
  %b Personas naturales:
  = @fund.personas_naturales
%p
  %b Personas juridicas con fines de lucro:
  = @fund.personas_juridicas_con_fines_de_lucro
%p
  %b Personas juridicas sin fines de lucro:
  = @fund.personas_juridicas_sin_fines_de_lucro
%p
  %b Donde se postula:
  = @fund.donde_se_postula
%p
  %b Areas tematicas de financiamiento:
  = @fund.areas_tematicas_de_financiamiento
%p
  %b Monto minimo:
  = @fund.monto_minimo
%p
  %b Monto maximo:
  = @fund.monto_maximo
%p
  %b Requisitos para postular:
  = @fund.requisitos_para_postular
%p
  %b Contacto:
  = @fund.contacto
%p
  %b Organizaciones participantes:
  = @fund.organizaciones_participantes

= link_to 'Edit', edit_fund_path(@fund)
\|
= link_to 'Back', funds_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      /= link_to 'ONGenerat.org', root_path, class: 'navbar-brand'
      %a{href: '/'}
        %img{:src => asset_path('assets/logo-ong-header.png'), :width => '250px' }
    .collapse.navbar-collapse
      /%ul.nav.navbar-nav
      /  = render 'layouts/navigation_links'
      /
        = link_to '1. Descúbrete', page_path('discover'), class: 'navbar-brand'
        = link_to '2. Existe', page_path('exist'), class: 'navbar-brand'
        = link_to '3. Funciona', funds_path, class: 'navbar-brand'
        = link_to '3.1. Parte legal (integrar en 3 y luego ocultar)', page_path('legal'), class: 'navbar-brand'
      = link_to 'Sobre nosotros', page_path('about'), class: 'navbar-brand pull-right'
      = link_to '<i class="fa fa-twitter"></i>'.html_safe, 'http://twitter.com/ciudadanoi', class: 'navbar-brand pull-right', target: '_blank'
      = link_to '<i class="fa fa-facebook"></i>'.html_safe, 'http://facebook.com/ciudadanointeligente', class: 'navbar-brand pull-right', target: '_blank'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'ONGenerator - Descúbrete, existe, funciona'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'ONGenerator'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %script{ :src => "//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js" }
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    /%div.containers
    = render 'layouts/messages'
    = yield

  / Footer
  %div.footer
    %p.text-center
      Desarrollado por
      %a{:href => "//www.ciudadanointeligente.org/", :target => "_blank"}
        %img{:alt => "Fundación Ciudadano Inteligente", :src => asset_path('assets/logo-ciudadanoi.png'), :title => "Fundación Ciudadano Inteligente"}/

app/views/pages/_filter_search_form.html.haml
= form_tag({controller: "funds", action: "searches"}, :method => 'get', :name => 'bills_search', :id => 'bills_search') do
  %div
    = label_tag :q, 'Palabra clave'
    %input.form-control{:name=>'q', :id=>'q', 'value' => params[:q], :placeholder => 'Comunidades indígenas'}

  %button.btn.btn-primary.pull-right.btn-lg
    Buscar

app/views/pages/about.html.erb
<% content_for :title do %>Sobre nosotros<% end %>
<h3>ONGenerator</h3>
<p>
Proyecto creado en la Visualizatón + Hackatón
<%= link_to('AbreCL', 'http://abrecl.datos.gob.cl/') %>
durante el 22 y 23 de noviembre de 2014.
</p>

app/views/pages/discover.html.erb
<div class="container">
  <div>
    <ol class="breadcrumb">
      <li>
        <a href="/">portada</a>
      </li>
      <li class="active">
        descúbrete
      </li>
      <li>
        <%= link_to 'existe', page_path('exist') %>
      </li>
      <li>
        <%= link_to 'funciona', funds_path %>
      </li>
    </ol>
  </div>

  <% content_for :title do %>Descúbrete<% end %>
  <h2 class="page-header">Descúbrete</h2>

  <h3 class="page-header">¿Por qué crear una organización civil?</h3>
  <ul>
    <li>No hay nadie que esté haciendo esto.</li>
    <li>Hay otros que están haciendo esto, pero con un enfoque y actividades diferentes. Nosotros lo podríamos hacer mejor.</li>
    <li>Porque queremos.</li>
  </ul>

  <h3 class="page-header">¿Cuál es el objeto social de la organización?</h3>
  <p>
    A qué se va a dedicar tu organización, aquí dejamos algunos ejemplos de temas a los que se puede dedicar una ONG:
  </p>
  <ul>
    <li>Asistencia social</li>
    <li>Apoyo a la alimentación popular</li>
    <li>Cívicas, enfocadas a promover la participación ciudadana en asuntos de interés público</li>
    <li>Asistencia jurídica</li>
    <li>Apoyo para el desarrollo de los pueblos y comunidades indígenas</li>
    <li>Promoción de la equidad de género</li>
    <li>Aportación de servicios para la atención a grupos sociales con discapacidad</li>
    <li>Cooperación para el desarrollo comunitario en el entorno urbano o rural</li>
    <li>Apoyo en la defensa y promoción de los derechos humanos</li>
    <li>Promoción del deporte</li>
    <li>Promoción y aportación de servicios para la atención de la salud y cuestiones sanitarias</li>
    <li>Apoyo en el aprovechamiento de los recursos naturales, la protección del ambiente, la flora y la fauna, la preservación y restauración del equilibrio ecológico, así como la promoción del desarrollo sustentable a nivel regional y comunitario, de las zonas urbanas y rurales</li>
    <li>Promoción y fomento educativo, cultural, artístico, científico y tecnológico</li>
    <li>Fomento de acciones para mejorar la economía popular</li>
    <li>Participación en acciones de protección civil</li>
    <li>Prestación de servicios de apoyo a la creación y fortalecimiento de organizaciones que realicen actividades objeto de fomento por esta ley</li>
    <li>Promoción y defensa de los derechos de los consumidores</li>
    <li>Acciones que promuevan el fortalecimiento del tejido social y la seguridad ciudadana</li>
  </ul>

  <h3 class="page-header">Preguntas Operacionales</h3>
  <ul>
    <li>Qué nombre le quieren poner?</li>
    <li>Qué tipo de miembros tendrá la organización?</li>
    <li>Quién será el representante legal de la organización.</li>
    <li>Decidir la estrategia de Financiamiento</li>
  </ul>

  <p class="text-center">
    <a href="//vizard-development.herokuapp.com/sandboxes/new" target="_blank" class="btn btn-success">Mapea tu Proceso</a>
  </p>

</div>

app/views/pages/exist.html.erb
<div class="container">
  <div>
    <ol class="breadcrumb">
      <li>
        <a href="/">portada</a>
      </li>
      <li>
        <%= link_to 'descúbrete', page_path('discover') %>
      </li>
      <li class="active">
        existe
      </li>
      <li>
        <%= link_to 'funciona', funds_path %>
      </li>
    </ul>
  </div>

  <% content_for :title do %>Existe<% end %>

  <h2 class="page-header">Existe</h2>

  <h3 class="page-header">¿Dónde se constituye una ONG?</h3>

  <p>En la secretaría municipal correspondiente al domicilio de la organización.</p>

  <h3 class="page-header">¿Quién registra la ONG en el Registro Civil?</h3>

  <p>El Secretario Municipal, representante del organismo público que constituyó una persona jurídica, el interesado o un representante de cualquiera de ellos.</p>

  <h3 class="page-header">¿Cómo se inscribe una ONG?</h3>

  <p>Tiene que llenar el formulario de solicitud de inscripción o su binscripción del “Registro Nacional de Personas Jurídicas sin fines de lucro”.</p>

  <p>El formulario y sus instrucciones de llenado están en el sitio web del Registro Civil</p>
  <ul>
    <li>descargue el <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.srcei.cl%2FServicios%2FRPJ%2FFormularios%2FFormulario_Solicitud_Ingreso.pdf&sa=D&sntz=1&usg=AFQjCNHJS0VH0-UZEDsv1SyYLhGg8P5hVg" target="_blank">Formulario de Inscripción <i class="fa fa-external-link"></i></a> (PDF del Registro Civil)</li>
    <li>descargue las Instrucciones de llenado <a href="http://www.google.com/url?q=http%3A%2F%2Fwww.srcei.cl%2FServicios%2FRPJ%2FFormularios%2FInstrucciones_de_llenado_formulario.pdf&sa=D&sntz=1&usg=AFQjCNHn53rEj19dl2AiSc3Fr6UAR3q-GA" target="_blank">Formulario de Inscripción <i class="fa fa-external-link"></i></a> (PDF del Registro Civil)</li>
  </ul>

  <h3 class="page-header">¿Qué hacer con el formulario?</h3>

  <p>El Secretario/a Municipal, representante del organismo público que constituyó una persona jurídica, el interesado o un representante de cualquiera de ellos debe concurrir las oficinas del Registro Civil y presentar el formulario ya citado, junto con los estatutos de constitución. El funcionario del Registro Civil procederá al preingreso de la solicitud. Importante tener presente que en los casos que sea el propio interesado quien concurra al Registro Civil debe contar con una autorización escrita emitida por el Secretario Municipal respectivo.</p>

  <h3 class="page-header">¿Para la constitución de una ONG se debe contar con la asesoría de un abogado?</h3>

  <p>No es necesaria la concurrencia de un abogado ya que el proceso de constitución en general se hace utilizando diversos Estatutos Modelo que explicitan claramente los procedimientos y documentos que se requieren para ello. En caso de no utilizar alguno de los 13 Estatutos Modelo (no es obligatorio usarlos) podría ser útil la presencia de un abogado considerando que se realizará una figura jurídica compleja que pudiese requerir su asesoría.</p>

  <h3 class="page-header">¿Dónde encuentro esos Estatutos Modelo?</h3>

  <a href="https://docs.google.com/document/d/1vpqz7wYCB_pg_aYK33ogqwx5AxqRzRMh1Tcg2SPmI44/edit?usp=sharing" target="_blank" class="btn btn-default">Descargalos acá</a>

  <h3 class="page-header">¿Si se utiliza el Estatuto Modelo el Secretario Muncipal puede objetar alguna de sus clausulas?</h3>

  <p>No, no puede objetar ninguna de sus clausulas.</p>

  <h3 class="page-header">¿Quién dirime en caso de que haya un desacuerdo entre el Secretario Municipal y el Registro Civil a la hora de aprobar la constitución de una ONG?</h3>

  <p>La última palabra la tiene el Registro Civil quien devolverá los documentos al Secretario Municipal para corregir los eventuales errores o agregar documentos faltantes.</p>

  <h3 class="page-header">¿Qué ocurre si un Secretario Municipal se niega a recibir la documentación entregada aduciendo desconocimiento, falta de tiempo u otra razón injustificada?</h3>

  <p>Puede presentar un reclamo ante el propio municipio, la Contraloría o un amparo ante los tribunales de justicia por denegación de derechos.</p>

  <h3 class="page-header">¿Quién entrega los certificados de vigencia de las ONG?</h3>

  <p>El ministerio de justicia entregará los certificados de vigencia hasta el 16 de febrero de 2013 para aquellas organizaciones que estaban inscritas antes del 16 de febrero de 2012. Para aquellas constituidas con posterioridad a esa fecha deben requerirla ante el Registro Civil. A partir del 16 de febrero de 2013 todos los certificados de vigencia los entregará únicamente el Registro Civil.</p>

  <h3 class="page-header">¿Cómo saber si se repite el mismo nombre con otra ONG lo que podría implicar el rechazo de mi solicitud?</h3>

  <p>Antes de asistir a la Secretaria Municipal a inscribir su ONG se sugiere ir directamente a la Unidad de Registro del departamento de persona jurídica del Ministerio de Justicia y consultar en sus registros si hay otra organización con un nombre similar.</p>
</div>

app/views/pages/work.html.erb
<% content_for :title do %>Funciona<% end %>
<h3>Funciona</h3>
<p>
  <h2>Busca un fondo adecuado a tus blabla</h2>
</p>

<form action="../funds/searches">
  Palabra clave:<br>
  <input type="text" name="palabraclave" value="Fondos indigenas">
  <br>
  Algo:<br>
  <input type="text" name="algo" value="Blabla">
  <br><br>
  <input type="submit" value="Enviar">
</form>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>

app/views/visitors/index.html.erb
<div class="container mainpage-header">
  <div class="container mainpage-cell">
    <div>
      <i class="fa fa-group fa-5x"></i>
      <h2>Súmate a la acción colectiva</h2>
      <p>
        Promovemos la asociatividad entre los ciudadanos, para que desde la sociedad civil organizada se pueda dar impulso a los cambios que queremos.
      </p>
      <p>
        <a href="#descubrete">descubrete</a> / <a href="#existe">existe</a> / <a href="#funciona">funciona</a>
      </p>
      <!--
      <div class="row">
        <div class="col-md-4">
          <p>
            <a href="#descubrete" class="btn btn-default"> <i class="fa fa-rocket fa-2x"></i>
            <br>
            Descúbrete
            </a>
          </p>
        </div>
        <div class="col-md-4">
          <p>
            <a href="#existe" class="btn btn-default">
              <i class="fa fa-leaf fa-2x"></i>
              <br>
              Existe
            </a>
          </p>
        </div>
        <div class="col-md-4">
          <p>
            <a href="#funciona" class="btn btn-default">
              <i class="fa fa-gears fa-2x"></i>
              <br>
              Funciona
            </a>
          </p>
        </div>
      </div>
      -->
    </div>
  </div>
</div>

<a name="descubrete"></a>
<div class="container mainpage-secondary">
  <div class="container mainpage-cell">
    <div>
      <i class="fa fa-rocket fa-5x"></i>
      <h2>Descúbrete</h2>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto dicta, praesentium. Ut consectetur, explicabo, praesentium unde necessitatibus ipsa assumenda amet dolores non quo quaerat ducimus iste sunt voluptatem molestias sint.
      </p>
      <%= link_to 'al infinito y más allá!', page_path('discover'), class: 'btn btn-default' %>
    </div>
  </div>
</div>

<a name="existe"></a>
<div class="container mainpage-third">
  <div class="container mainpage-cell">
    <div>
      <i class="fa fa-leaf fa-5x"></i>
      <h2>Existe</h2>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto dicta, praesentium. Ut consectetur, explicabo, praesentium unde necessitatibus ipsa assumenda amet dolores non quo quaerat ducimus iste sunt voluptatem molestias sint.
      </p>
      <%= link_to 'a por ello!', page_path('exist'), class: 'btn btn-default' %>
    </div>
  </div>
</div>

<a name="funciona"></a>
<div class="container mainpage-four">
  <div class="container mainpage-cell">
    <div>
      <i class="fa fa-gears fa-5x"></i>
      <h2>Funciona</h2>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto dicta, praesentium. Ut consectetur, explicabo, praesentium unde necessitatibus ipsa assumenda amet dolores non quo quaerat ducimus iste sunt voluptatem molestias sint.
      </p>
      <%= link_to 'encuentra tu fondo', funds_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>
<script>
  $(function() {
    $('a[href*=#]:not([href=#])').click(function() {
      if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
        var target = $(this.hash);
        target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
        if (target.length) {
          $('html,body').animate({
            scrollTop: target.offset().top
          }, 1000);
          return false;
        }
      }
    });
  });
</script>